Deployment  diagram
Arquisoft/lomap_en3a pull request #100
Opened 2023-04-11 18:01 UTC by Pelayo-Reguera

A table with a small description of each component will be added in a moment

2023-04-11 19:14 UTC, uo282892 requested changes
The database is on the cloud (MongoDB Atlas), and you should draw a connection from the restapi to there.

Then, the POD is provided by Inrupt,so you could do the same drawing as in the database.

The webapp and the restapi are on separate containers inside the Azure machine.

2023-04-12 06:33 UTC, uo282892 reviewed
I would put that the connection to the pod is from the webapp, not just the server. The same with the database and the restapi

2023-04-12 09:26 UTC, Pelayo-Reguera commented
> I would put that the connection to the pod is from the webapp, not just the server. The same with the database and the restapi

Yes, it's true. Later I'll change it

2023-04-12 15:35 UTC, UO283428 approved these changes

2023-04-12 20:39 UTC, UO283428 approved these changes

2023-04-12 20:40 UTC, UO283069 approved these changes

2023-04-12 20:59 UTC, uo282892 approved these changes

2023-04-12 21:01 UTC, Davidmc07 approved these changes

2023-04-12 21:01 UTC, merged